# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://shylagangwar1911.github.io
title: Shyla Gangwar
email: sgangwar@cs.umass.edu 
author: Shyla Gangwar
description: > # "Write an awesome description for your new site here. 
  Personal website of Shyla Gangwar, MS student at UMass Amherst
copyright: 'Copyright &copy; 2019 Shyla Gangwar. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: sgangwar@cs.umass.edu 
  - title: github
    url: https://github.com/shylagangwar1911
  - title: linkedin
    url: https://www.linkedin.com/in/shylagangwar/
